export const WORDS = [
  { word: 'Pies', hint: 'Udomowiony, bestia człowieka' },
  { word: 'Kot', hint: 'Niezależne, furkające stworzenie' },
  { word: 'Słoń', hint: 'Ogromne stworzenie z trąbą' },
  { word: 'Pingwin', hint: 'Czarno-biały ptak z Antarktydy' },
  { word: 'Żyrafa', hint: 'Długa szyja, afrykańskie zwierzę' },
  { word: 'Lew', hint: 'Król zwierząt, szyja' },
  { word: 'Tygrys', hint: 'Pomarańczowy z czarnymi paskami' },
  { word: 'Niedźwiedź', hint: 'Wielkie furkające zwierze' },
  { word: 'Wąż', hint: 'Gad bez nóg' },
  { word: 'Orzeł', hint: 'Duży ptak drapieżny' },
  { word: 'Żaba', hint: 'Przeskakuje, żyje w wodzie' },
  { word: 'Pająk', hint: 'Osiem nóg, pajakowiec' },
  { word: 'Motyl', hint: 'Owad z kolorowymi skrzydłami' },
  { word: 'Pszczoła', hint: 'Zbiera nektar i robi miód' },
  { word: 'Ryba', hint: 'Żyje w wodzie, ma skrzela' },
  { word: 'Delfin', hint: 'Inteligentny ssak morski' },
  { word: 'Wieloryb', hint: 'Największy zwierz na Ziemi' },
  { word: 'Krowa', hint: 'Daje mleko, robi muuu' },
  { word: 'Świnia', hint: 'Różowa, lubi błoto' },
  { word: 'Kurczak', hint: 'Ptak, daje jaja' },
  { word: 'Konia', hint: 'Szybkie, jeździmy na nim' },
  { word: 'Gęś', hint: 'Duży ptak wodny' },
  { word: 'Ptak', hint: 'Latający, ma skrzydła' },
  { word: 'Mysz', hint: 'Mała, szara, boi się kota' },
  { word: 'Królik', hint: 'Biały, długie uszy' },
  { word: 'Żółw', hint: 'Powolny, pancerny' },
  { word: 'Krokodyl', hint: 'Zielony, duże zęby' },
  { word: 'Hippopotam', hint: 'Duży, żyje w wodzie' },
  { word: 'Zebra', hint: 'Czarno-białe paski' },
  { word: 'Nosorożec', hint: 'Duży, róg na nosie' },
  { word: 'Małpa', hint: 'Śmieszna, grymaśna' },
  { word: 'Lama', hint: 'Alpaka, jedno y' },
  { word: 'Ptak kolibri', hint: 'Najmniejszy ptak, szybko bije skrzydłami' },
  { word: 'Struś', hint: 'Nie lata, biegiem szybki' },
  { word: 'Fenix', hint: 'Mityczny ptak z ognia' },
  { word: 'Smok', hint: 'Mityczne zwierzę z ogniem' },
  { word: 'Jednorożec', hint: 'Mityczne, róg na czole' },
  { word: 'Foka', hint: 'Morskie zwierzę, bije się z piłką' },
  { word: 'Medusa', hint: 'Morskie, żrące macki' },
  { word: 'Pizza', hint: 'Włoskie danie z serkiem i sosem' },
  { word: 'Sushi', hint: 'Japońskie, ryż z rybą' },
  { word: 'Burger', hint: 'Kanapka z mięsem' },
  { word: 'Lody', hint: 'Chłodny deser' },
  { word: 'Pasta', hint: 'Włoskie makaron' },
  { word: 'Chleb', hint: 'Piekarniczy, pokrojony' },
  { word: 'Sernik', hint: 'Deser z serem' },
  { word: 'Piernik', hint: 'Świąteczny przysmak' },
  { word: 'Żurek', hint: 'Polski żur' },
  { word: 'Bigos', hint: 'Kapusniak z mięsem' },
  { word: 'Śledź', hint: 'Rybka, tradycyjna' },
  { word: 'Oscypek', hint: 'Górski ser' },
  { word: 'Zapiekanka', hint: 'Chleb z zalewą' },
  { word: 'Mleczko', hint: 'Deser do jedzenia łyżką' },
  { word: 'Placki', hint: 'Kartoflane polskie' },
  { word: 'Kotlety', hint: 'Mielone, mięsne' },
  { word: 'Kluski', hint: 'Do zupy' },
  { word: 'Pierogi', hint: 'Polski kluski z nadzieniem' },
  { word: 'Kielbasa', hint: 'Polska parówka' },
  { word: 'Rosół', hint: 'Bulion z kurczaka' },
  { word: 'Schab', hint: 'Mięso wieprzowe' },
  { word: 'Steak', hint: 'Grillowany kawałek mięsa' },
  { word: 'Paczki', hint: 'Pyszne, słodkie' },
  { word: 'Donut', hint: 'Okrągły, dziura w środku' },
  { word: 'Kompot', hint: 'Napój z owoców' },
  { word: 'Mleko', hint: 'Biały napój' },
  { word: 'Kawa', hint: 'Czarny gorący napój' },
  { word: 'Herbata', hint: 'Gorący napój z liści' },
  { word: 'Piwo', hint: 'Alkoholowy napój' },
  { word: 'Wino', hint: 'Z winogron, alkoholowy' },
  { word: 'Sok', hint: 'Z owoców, słodki' },
  { word: 'Czekolada', hint: 'Brązowa, słodka' },
  { word: 'Ciastka', hint: 'Małe, słodkie' },
  { word: 'Owoce', hint: 'Słodkie, z drzew' },
  { word: 'Warzywa', hint: 'Zdrowe, z gruntu' },
  { word: 'Polska', hint: 'Kraj w Europie Środkowej' },
  { word: 'Japonia', hint: 'Wyspa w Azji' },
  { word: 'Brazylia', hint: 'Wielki kraj w Ameryce Południowej' },
  { word: 'Niemcy', hint: 'Kraj w środku Europy' },
  { word: 'Norwegia', hint: 'Kraj fjordów' },
  { word: 'Włochy', hint: 'Península, Roma' },
  { word: 'Francja', hint: 'Paryż, wino' },
  { word: 'Anglia', hint: 'Brytania, Londyn' },
  { word: 'Hiszpania', hint: 'Flamenco, śródziemnomorska' },
  { word: 'Grecja', hint: 'Ateny, wysypę' },
  { word: 'Rosja', hint: 'Najduży kraj' },
  { word: 'Chiny', hint: 'Wielki mur, dynastia' },
  { word: 'Indie', hint: 'Taj Mahal, curry' },
  { word: 'Kanada', hint: 'Niagara, liść' },
  { word: 'USA', hint: 'Ameryka, statki' },
  { word: 'Meksyk', hint: 'Sombreros, tacos' },
  { word: 'Australia', hint: 'Kangury, bumerangi' },
  { word: 'Nowa Zelandia', hint: 'Hobbiton' },
  { word: 'Szwecja', hint: 'Nordyk, ikea' },
  { word: 'Dania', hint: 'Skandynawski, cukiernie' },
  { word: 'Turcja', hint: 'Bawełna, orientalne' },
  { word: 'Gruzja', hint: 'Kaukaz, wino' },
  { word: 'Ukraina', hint: 'Słoneczniki, pszenica' },
  { word: 'Rumunia', hint: 'Karpaty, Dracula' },
  { word: 'Portugalia', hint: 'Fado, kork' },
  { word: 'Holandia', hint: 'Wiatraki, tulipany' },
  { word: 'Belgia', hint: 'Czekolada, czeskie' },
  { word: 'Szwajcaria', hint: 'Góry, ser, zegary' },
  { word: 'Austria', hint: 'Alpy, opera' },
  { word: 'Czechy', hint: 'Praga, piwo' },
  { word: 'Węgry', hint: 'Budapeszt, goulash' },
  { word: 'Słowacja', hint: 'Tatry, zamki' },
  { word: 'Litwa', hint: 'Wilno, na wschodzie' },
  { word: 'Łotwa', hint: 'Ryga, bursztyn' },
  { word: 'Estonia', hint: 'Tallinn, digital' },
  { word: 'Piłka nożna', hint: 'Gra z piłką i bramkami' },
  { word: 'Tenis', hint: 'Rakietka i mała piłeczka' },
  { word: 'Pływanie', hint: 'Ruch w wodzie' },
  { word: 'Koszykówka', hint: 'Gra z kosem i piłką' },
  { word: 'Skoki narciarskie', hint: 'Skakanie ze skoków' },
  { word: 'Voleyball', hint: 'Siatka, odbijanie' },
  { word: 'Hokej', hint: 'Krążek, kija' },
  { word: 'Bieganie', hint: 'Maraton, sprint' },
  { word: 'Jazda na rowerze', hint: 'Pedały, łańcuch' },
  { word: 'Judo', hint: 'Japoński sport walki' },
  { word: 'Boks', hint: 'Walka, rękawice' },
  { word: 'Łucznictwo', hint: 'Strzały, łuk' },
  { word: 'Golf', hint: 'Pałeczka, dołek' },
  { word: 'Badminton', hint: 'Piórko, rakietka' },
  { word: 'Tenis stołowy', hint: 'Ping pong' },
  { word: 'Gimnastyka', hint: 'Ćwiczenia, elastyczność' },
  { word: 'Łyżwiarstwo', hint: 'Lód, szybkość' },
  { word: 'Figura łyżwowa', hint: 'Piękne ruchy na lodzie' },
  { word: 'Rodeo', hint: 'Koń, wstęga' },
  { word: 'Wspinaczka', hint: 'Góry, lina' },
  { word: 'Karate', hint: 'Martil arts, karate' },
  { word: 'Catch', hint: 'Walka, ring' },
  { word: 'Szachmat', hint: 'Gra umysłu, królestwa' },
  { word: 'Bilard', hint: 'Kule, stół' },
  { word: 'Bowling', hint: 'Kegielnia, kula' },
  { word: 'Avatar', hint: 'Pandora, niebiescy ludzie' },
  { word: 'Titanic', hint: 'Statek, lodowiec' },
  { word: 'Incepcja', hint: 'Marzenia w marzeniach' },
  { word: 'Matrix', hint: 'Kapsułki, świat wirtualny' },
  { word: 'Gwiezdne Wojny', hint: 'Kosmos, miecze świetlne' },
  { word: 'Harry Potter', hint: 'Czarodzieje, szkoła' },
  { word: 'Władca Pierścieni', hint: 'Pierścień, hobbici' },
  { word: 'Avengers', hint: 'Superbohaterowie, zespół' },
  { word: 'Interstellar', hint: 'Kosmos, miłość' },
  { word: 'Forrest Gump', hint: 'Biegnę, ławka' },
  { word: 'Shawshank Redemption', hint: 'Więzienie, ucieczeńka' },
  { word: 'Pulp Fiction', hint: 'Kriminalny, historia' },
  { word: 'Gladiator', hint: 'Rzym, arena' },
  { word: 'Jaws', hint: 'Rekin, plaża' },
  { word: 'E.T.', hint: 'Obcy, telefon' },
  { word: 'Backtothefuture', hint: 'Maszyna czasu, samochód' },
  { word: 'Jurassic Park', hint: 'Dinozaury, wyspa' },
  { word: 'Groza', hint: 'Hotel, szaleństwo' },
  { word: 'Czarownica z Zachodu', hint: 'Zielona, woda' },
  { word: 'Czarny Łabędź', hint: 'Balet, szaleństwo' },
  { word: 'Shrek', hint: 'Ogrze, bąbelki' },
  { word: 'Frozen', hint: 'Lód, siostry' },
  { word: 'Lion King', hint: 'Afryka, lew' },
  { word: 'Pinocchio', hint: 'Drewniana marionetka' },
  { word: 'Cinderella', hint: 'Słoneczka, bal' },
  { word: 'Beauty and Beast', hint: 'Róża, różyczka' },
  { word: 'Aladdin', hint: 'Lampa, geniusz' },
  { word: 'Mulan', hint: 'Chiny, dziewczyna żołnierz' },
  { word: 'Hercules', hint: 'Grecja, bohater' },
  { word: 'Gitara', hint: 'Struny, muzyka rockowa' },
  { word: 'Fortepian', hint: 'Klawisze, muzyka poważna' },
  { word: 'Bęben', hint: 'Perkusja, głośny' },
  { word: 'Skrzypce', hint: 'Smyczek, muzyka klasyczna' },
  { word: 'Trąbka', hint: 'Metal, jazz' },
  { word: 'Flet', hint: 'Drewniany, wiatrowy' },
  { word: 'Obój', hint: 'Drewniany, reedy' },
  { word: 'Klarnet', hint: 'Drewniany, jazz' },
  { word: 'Saksofon', hint: 'Metal, jazzowy' },
  { word: 'Wiolonczela', hint: 'Duży, stroikowy' },
  { word: 'Kontrabas', hint: 'Największy, grający' },
  { word: 'Mandolina', hint: 'Mała, włoska' },
  { word: 'Harfa', hint: 'Struny, kąt' },
  { word: 'Organy', hint: 'Duże, kościoły' },
  { word: 'Akordeon', hint: 'Przyciskami, tradycyjny' },
  { word: 'Harmonijka', hint: 'Mała, ustna' },
  { word: 'Perkusja', hint: 'Uderzanie, rytm' },
  { word: 'Tympany', hint: 'Kotły, orkiestra' },
  { word: 'Talerze', hint: 'Metalowe, wiszące' },
  { word: 'Xylofon', hint: 'Drewniane, klawisze' },
  { word: 'Warszawa', hint: 'Polska stolica' },
  { word: 'Kraków', hint: 'Polska, stara' },
  { word: 'Nowy Jork', hint: 'Wieżowce, wielkie' },
  { word: 'Londyn', hint: 'Anglia, Big Ben' },
  { word: 'Paryż', hint: 'Francja, Eiffel' },
  { word: 'Tokio', hint: 'Japonia, stolica' },
  { word: 'Pekin', hint: 'Chiny, wielki mur' },
  { word: 'Mumbai', hint: 'Indie, bollyywood' },
  { word: 'Sydney', hint: 'Australia, opera' },
  { word: 'Rio de Janeiro', hint: 'Brazylia, karnawał' },
  { word: 'Barcelona', hint: 'Spanija, Sagrada' },
  { word: 'Berlin', hint: 'Niemcy, mur' },
  { word: 'Rzym', hint: 'Włochy, Koloseum' },
  { word: 'Wenecja', hint: 'Włochy, kanały' },
  { word: 'Amsterdam', hint: 'Holandia, rowery' },
  { word: 'Mediolan', hint: 'Włochy, moda' },
  { word: 'Madryt', hint: 'Spanija, stolica' },
  { word: 'Ateny', hint: 'Grecja, wysypę' },
  { word: 'Sztokholm', hint: 'Szwecja, wysypę' },
  { word: 'Dubaj', hint: 'Zjednoczone Emiraty, burj' },
  { word: 'Telefon', hint: 'Ekran dotykowy, połączenia' },
  { word: 'Komputer', hint: 'Klawiszownia, mysz' },
  { word: 'Internet', hint: 'Sieć światowa' },
  { word: 'Laptop', hint: 'Przenośny komputer' },
  { word: 'Tablet', hint: 'Jak laptop ale mniejszy' },
  { word: 'Słuchawki', hint: 'Dźwięk do uszu' },
  { word: 'Kamera', hint: 'Foto, video' },
  { word: 'Drukarka', hint: 'Papierowy output' },
  { word: 'Monitor', hint: 'Ekran do komputera' },
  { word: 'Router', hint: 'WiFi, internet' },
  { word: 'Dysk twardy', hint: 'Przechowywanie danych' },
  { word: 'Pendrive', hint: 'Mały, przenosny' },
  { word: 'Bateria', hint: 'Energia dla urządzenia' },
  { word: 'Ładowarka', hint: 'Energia do urządzenia' },
  { word: 'Telewizor', hint: 'Duży ekran do oglądania' },
  { word: 'Konsola', hint: 'Gry wideo' },
  { word: 'Mikrofon', hint: 'Nagrywanie głosu' },
  { word: 'Skanery', hint: 'Czytanie dokumentów' },
  { word: 'Projektor', hint: 'Obrazy na ścianę' },
  { word: 'Dron', hint: 'Latające urządzenie' },
  { word: 'Robot', hint: 'Sztuczna inteligencja' },
  { word: 'Smartwatch', hint: 'Zegarek, inteligentny' },
  { word: 'Las', hint: 'Drzewa, zwierzęta' },
  { word: 'Góra', hint: 'Wysoka, alpinizm' },
  { word: 'Rzeka', hint: 'Płynąca woda' },
  { word: 'Jezioro', hint: 'Stojąca woda' },
  { word: 'Morze', hint: 'Slona woda, fale' },
  { word: 'Ocean', hint: 'Ogromna woda' },
  { word: 'Plaża', hint: 'Piasek, morze' },
  { word: 'Pustynia', hint: 'Piaski, sucho' },
  { word: 'Tundra', hint: 'Mróz, arcktyka' },
  { word: 'Sawanna', hint: 'Afryka, trawy' },
  { word: 'Dżungla', hint: 'Gęsty las' },
  { word: 'Wulkan', hint: 'Lawa, gorąco' },
  { word: 'Jaskinia', hint: 'Podziemna' },
  { word: 'Wodospad', hint: 'Padająca woda' },
  { word: 'Chmura', hint: 'W niebie, woda' },
  { word: 'Burza', hint: 'Grzmot, błyskawica' },
  { word: 'Śnieg', hint: 'Biały, zima' },
  { word: 'Lód', hint: 'Zamrożona woda' },
  { word: 'Grad', hint: 'Ciężkie kulki lodu' },
  { word: 'Tęcza', hint: 'Kolorowa, po deszczu' },
  { word: 'Rock', hint: 'Gitary, energiczny' },
  { word: 'Pop', hint: 'Popularna, katchy' },
  { word: 'Rap', hint: 'Rymowanka, beat' },
  { word: 'Jazz', hint: 'Improwizacyjny, trąbka' },
  { word: 'Blues', hint: 'Smutny, gitara' },
  { word: 'Klasyka', hint: 'Poważna, orkiestra' },
  { word: 'Elektronika', hint: 'Syntezer, DJ' },
  { word: 'Metal', hint: 'Agresywny rock' },
  { word: 'Country', hint: 'Wiejski, gitary' },
  { word: 'Reggae', hint: 'Jamajki, ritm' },
  { word: 'Hip-Hop', hint: 'Rap, kultura' },
  { word: 'R&B', hint: 'Soul, melodyjny' },
  { word: 'Techno', hint: 'Pulsujący, taniec' },
  { word: 'House', hint: 'Taneczny, party' },
  { word: 'Opera', hint: 'Śpiewana sztuka' },
  { word: 'Ludowa', hint: 'Tradycyjna, taniec' },
  { word: 'Soul', hint: 'Emocjonalna, głos' },
  { word: 'Funk', hint: 'Groovy, taneczne' },
  { word: 'Indie', hint: 'Niezależna, alternatywa' },
  { word: 'Punk', hint: 'Rebelia, szybka' },
  { word: 'Disney', hint: 'Animacja, magia' },
  { word: 'Netflix', hint: 'Streaming, filmy' },
  { word: 'YouTube', hint: 'Wideo, kanały' },
  { word: 'TikTok', hint: 'Krótkie filmy, taniec' },
  { word: 'Instagram', hint: 'Foto, media społeczne' },
  { word: 'Facebook', hint: 'Społeczność, stara' },
  { word: 'Twitter', hint: 'Tweety, wiadomości' },
  { word: 'Snapchat', hint: 'Filtery, znikające' },
  { word: 'Telegram', hint: 'Chat, szybki' },
  { word: 'WhatsApp', hint: 'Wiadomości, zielony' },
  { word: 'Discord', hint: 'Gamerzy, serwery' },
  { word: 'Reddit', hint: 'Koty, mem' },
  { word: 'Twitch', hint: 'Streaming, gry' },
  { word: 'Wikipedia', hint: 'Encyklopedia, wiki' },
  { word: 'Google', hint: 'Wyszukiwarka, czasami' },
  { word: 'Amazon', hint: 'Zakupy, paczka' },
  { word: 'Apple', hint: 'iPhone, jabłko' },
  { word: 'Microsoft', hint: 'Windows, Office' },
  { word: 'Tesla', hint: 'Samochód, elektryk' },
  { word: 'Nike', hint: 'Buty sportowe' },
  { word: 'Adidas', hint: 'Paski, sportowe' },
  { word: 'Coca-Cola', hint: 'Napój, czerwone' },
  { word: 'McDonald', hint: 'Hamburgery, złote łuki' },
  { word: 'Burger King', hint: 'Burgery, korona' },
  { word: 'Pizza Hut', hint: 'Pizza, dach' },
  { word: 'Starbucks', hint: 'Kawa, syrenka' },
  { word: 'IKEA', hint: 'Mebli, Szwecja' },
  { word: 'H&M', hint: 'Moda, szybka' },
  { word: 'Zara', hint: 'Ubrania, szpańska' },
  { word: 'Gucci', hint: 'Luksus, włoska' },
  { word: 'Louis Vuitton', hint: 'Luksus, torebki' },
  { word: 'Ferrari', hint: 'Czerwony, szybki' },
  { word: 'Lamborghini', hint: 'Supersamochód, żółty' },
  { word: 'Porsche', hint: 'Luksus, niemiecki' },
  { word: 'Rolex', hint: 'Zegarek, drogi' },
  { word: 'Swarovski', hint: 'Kryształy, błyszczące' },
  { word: 'Dior', hint: 'Moda, perfumy' },
  { word: 'Chanel', hint: 'Moda, numer 5' },
  { word: 'Versace', hint: 'Moda, głów meduzy' },
  { word: 'Prada', hint: 'Moda, włoska' },
];

export function getRandomWord(): { word: string; hint: string } {
  if (WORDS.length === 0) {
    return { word: 'Sekret', hint: 'Niespodziewane' };
  }
  const randomWord = WORDS[Math.floor(Math.random() * WORDS.length)];
  return randomWord;
}
