export const WORD_CATEGORIES = {
  Zwierzęta: [
    { word: 'Pies', hint: 'Udomowiony, bestia człowieka' },
    { word: 'Kot', hint: 'Niezależne, furkające stworzenie' },
    { word: 'Słoń', hint: 'Ogromne stworzenie z trąbą' },
    { word: 'Pingwin', hint: 'Czarno-biały ptak z Antarktydy' },
    { word: 'Żyrafa', hint: 'Długa szyja, afrykańskie zwierzę' },
    { word: 'Lew', hint: 'Król zwierząt, szyja' },
    { word: 'Tygrys', hint: 'Pomarańczowy z czarnymi paskami' },
    { word: 'Niedźwiedź', hint: 'Wielkie furkające zwierze' },
    { word: 'Wąż', hint: 'Gad bez nóg' },
    { word: 'Orzeł', hint: 'Duży ptak drapieżny' },
    { word: 'Żaba', hint: 'Przeskakuje, żyje w wodzie' },
    { word: 'Pająk', hint: 'Osiem nóg, pajakowiec' },
    { word: 'Motyl', hint: 'Owad z kolorowymi skrzydłami' },
    { word: 'Pszczoła', hint: 'Zbiera nektar i robi miód' },
    { word: 'Ryba', hint: 'Żyje w wodzie, ma skrzela' },
    { word: 'Delfin', hint: 'Inteligentny ssak morski' },
    { word: 'Wieloryb', hint: 'Największy zwierz na Ziemi' },
    { word: 'Krowa', hint: 'Daje mleko, robi muuu' },
    { word: 'Świnia', hint: 'Różowa, lubi błoto' },
    { word: 'Kurczak', hint: 'Ptak, daje jaja' },
  ],
  Jedzenie: [
    { word: 'Pizza', hint: 'Włoskie danie z serkiem i sosem' },
    { word: 'Sushi', hint: 'Japońskie, ryż z rybą' },
    { word: 'Burger', hint: 'Kanapka z mięsem' },
    { word: 'Lody', hint: 'Chłodny deser' },
    { word: 'Pasta', hint: 'Włoskie makaron' },
    { word: 'Chleb', hint: 'Piekarniczy, pokrojony' },
    { word: 'Sernik', hint: 'Deser z serem' },
    { word: 'Piernik', hint: 'Świąteczny przysmak' },
    { word: 'Żurek', hint: 'Polski żur' },
    { word: 'Bigos', hint: 'Kapusniak z mięsem' },
    { word: 'Śledź', hint: 'Rybka, tradycyjna' },
    { word: 'Oscypek', hint: 'Górski ser' },
    { word: 'Zapiekanka', hint: 'Haluszki z zalewą' },
    { word: 'Mleczko', hint: 'Deser do jedzenia łyżką' },
    { word: 'Placki', hint: 'Kartoflane polskie' },
    { word: 'Kotlety', hint: 'Mielone, mięsne' },
    { word: 'Kluski', hint: 'Do zupy' },
    { word: 'Pierogi', hint: 'Polski kluski z nadzieniem' },
    { word: 'Kielbasa', hint: 'Pork, Polish sausage' },
    { word: 'Rosół', hint: 'Bulion z kurczaka' },
  ],
  Kraje: [
    { word: 'Polska', hint: 'Kraj w Europie Środkowej' },
    { word: 'Japonia', hint: 'Wyspa w Azji' },
    { word: 'Brazylia', hint: 'Wielki kraj w Ameryce Południowej' },
    { word: 'Niemcy', hint: 'Kraj w środku Europy' },
    { word: 'Norwegia', hint: 'Kraj fjordów' },
    { word: 'Włochy', hint: 'Península, Roma' },
    { word: 'Francja', hint: 'Paryż, wino' },
    { word: 'Anglia', hint: 'Brytania, Londyn' },
    { word: 'Hiszpania', hint: 'Flamenco, śródziemnomorska' },
    { word: 'Grecja', hint: 'Ateny, wysypę' },
    { word: 'Rosja', hint: 'Najduży kraj' },
    { word: 'Chiny', hint: 'Wielki mur, dynastia' },
    { word: 'Indie', hint: 'Taj Mahal, curry' },
    { word: 'Kanada', hint: 'Niagara, liść' },
    { word: 'USA', hint: 'Ameryka, statki' },
    { word: 'Meksyk', hint: 'Sombreros, tacos' },
    { word: 'Australia', hint: 'Kangury, bumerangi' },
    { word: 'Nowa Zelandia', hint: 'Hobbiton' },
    { word: 'Szwecja', hint: 'Nordyk, ikea' },
    { word: 'Dania', hint: 'Skandynawski, cukiernie' },
  ],
  Sport: [
    { word: 'Piłka nożna', hint: 'Gra z piłką i bramkami' },
    { word: 'Tenis', hint: 'Rakietka i mała piłeczka' },
    { word: 'Pływanie', hint: 'Ruch w wodzie' },
    { word: 'Koszykówka', hint: 'Gra z kosem i piłką' },
    { word: 'Skoki narciarskie', hint: 'Skakanie ze skoków' },
    { word: 'Voleyball', hint: 'Siatka, odbijanie' },
    { word: 'Hokej', hint: 'Krążek, kija' },
    { word: 'Bieganie', hint: 'Maraton, sprint' },
    { word: 'Jazda na rowerze', hint: 'Pedały, łańcuch' },
    { word: 'Judo', hint: 'Japoński sport walki' },
    { word: 'Boks', hint: 'Walka, rękawice' },
    { word: 'Łucznictwo', hint: 'Strzały, łuk' },
    { word: 'Golf', hint: 'Pałeczka, dołek' },
    { word: 'Badminton', hint: 'Piórko, rakietka' },
    { word: 'Tenis stołowy', hint: 'Ping pong' },
    { word: 'Gimnastyka', hint: 'Ćwiczenia, elastyczność' },
    { word: 'Łyżwiarstwo', hint: 'Lód, szybkość' },
    { word: 'Figura łyżwowa', hint: 'Piękne ruchy na lodzie' },
    { word: 'Rodeo', hint: 'Koń, wstęga' },
    { word: 'Wspinaczka', hint: 'Góry, lina' },
  ],
  Filmy: [
    { word: 'Avatar', hint: 'Pandora, niebiescy ludzie' },
    { word: 'Titanic', hint: 'Statek, lodowiec' },
    { word: 'Incepcja', hint: 'Marzenia w marzeniach' },
    { word: 'Matrix', hint: 'Kapsułki, świat wirtualny' },
    { word: 'Gwiezdne Wojny', hint: 'Kosmos, miecze świetlne' },
    { word: 'Harry Potter', hint: 'Czarodzieje, szkoła' },
    { word: 'Władca Pierścieni', hint: 'Pierścień, hobbici' },
    { word: 'Avengers', hint: 'Superbohaterowie, zespół' },
    { word: 'Interstellar', hint: 'Kosmos, miłość' },
    { word: 'Forrest Gump', hint: 'Biegnę, ławka' },
    { word: 'Shawshank Redemption', hint: 'Więzienie, ucieczeńka' },
    { word: 'Pulp Fiction', hint: 'Kriminalny, historia' },
    { word: 'Gladiator', hint: 'Rzym, arena' },
    { word: 'Jaws', hint: 'Rekin, plaża' },
    { word: 'E.T.', hint: 'Obcy, telefon' },
    { word: 'Backtothefuture', hint: 'Maszyna czasu, samochód' },
    { word: 'Jurassic Park', hint: 'Dinozaury, wyspa' },
    { word: 'Groza', hint: 'Hotel, szaleństwo' },
    { word: 'Czarownica z Zachodu', hint: 'Zielona, woda' },
    { word: 'Czarny Łabędź', hint: 'Balet, szaleństwo' },
  ],
  Instrumenty: [
    { word: 'Gitara', hint: 'Struny, muzyka rockowa' },
    { word: 'Fortepian', hint: 'Klawisze, muzyka poważna' },
    { word: 'Bęben', hint: 'Perkusja, głośny' },
    { word: 'Skrzypce', hint: 'Smyczek, muzyka klasyczna' },
    { word: 'Trąbka', hint: 'Metal, jazz' },
    { word: 'Flet', hint: 'Drewniany, wiatrowy' },
    { word: 'Obój', hint: 'Drewniany, reedy' },
    { word: 'Klarnet', hint: 'Drewniany, jazz' },
    { word: 'Saksofon', hint: 'Metal, jazzowy' },
    { word: 'Wiolonczela', hint: 'Duży, stroikowy' },
    { word: 'Kontrabas', hint: 'Największy, grający' },
    { word: 'Mandolina', hint: 'Mała, włoska' },
    { word: 'Harfa', hint: 'Struny, kąt' },
    { word: 'Organy', hint: 'Duże, kościoły' },
    { word: 'Akordeon', hint: 'Przyciskami, tradycyjny' },
    { word: 'Harmonijka', hint: 'Mała, ustna' },
    { word: 'Perkusja', hint: 'Uderzanie, rytm' },
    { word: 'Tympany', hint: 'Kotły, orkiestra' },
    { word: 'Talerze', hint: 'Metalowe, wiszące' },
    { word: 'Xylofon', hint: 'Drewniane, klawisze' },
  ],
  Miasta: [
    { word: 'Warszawa', hint: 'Polska stolica' },
    { word: 'Kraków', hint: 'Polska, stara' },
    { word: 'Nowy Jork', hint: 'Wieżowce, wielkie' },
    { word: 'Londyn', hint: 'Англия, Big Ben' },
    { word: 'Paryż', hint: 'Francja, Eiffel' },
    { word: 'Tokio', hint: 'Japonia, stolica' },
    { word: 'Pekin', hint: 'Chiny, wielki mur' },
    { word: 'Mumbai', hint: 'Indie, bollyywood' },
    { word: 'Sydney', hint: 'Australia, opera' },
    { word: 'Rio de Janeiro', hint: 'Brazylia, karnawał' },
    { word: 'Barcelona', hint: 'Španija, Sagrada' },
    { word: 'Berlin', hint: 'Niemcy, mur' },
    { word: 'Rzym', hint: 'Włochy, Koloseum' },
    { word: 'Wenecja', hint: 'Włochy, kanały' },
    { word: 'Amsterdam', hint: 'Holandia, rowery' },
    { word: 'Mediolan', hint: 'Włochy, moda' },
    { word: 'Madryt', hint: 'Spanija, stolica' },
    { word: 'Ateny', hint: 'Grecja, wysypę' },
    { word: 'Sztokholm', hint: 'Szwecja, wysypę' },
    { word: 'Dubaj', hint: 'Zjednoczone Emiraty, burj' },
  ],
  Technologia: [
    { word: 'Telefon', hint: 'Ekran dotykowy, połączenia' },
    { word: 'Komputer', hint: 'Klawiszownia, mysz' },
    { word: 'Internet', hint: 'Sieć światowa' },
    { word: 'Laptop', hint: 'Przenośny komputer' },
    { word: 'Tablet', hint: 'Jak laptop ale mniejszy' },
    { word: 'Słuchawki', hint: 'Dźwięk do uszu' },
    { word: 'Kamera', hint: 'Foto, video' },
    { word: 'Drukarka', hint: 'Papierowy output' },
    { word: 'Monitor', hint: 'Ekran do komputera' },
    { word: 'Router', hint: 'WiFi, internet' },
    { word: 'Dysk twardy', hint: 'Przechowywanie danych' },
    { word: 'Pendrive', hint: 'Mały, przenosny' },
    { word: 'Bateria', hint: 'Energia dla urządzenia' },
    { word: 'Ładowarka', hint: 'Energia do urządzenia' },
    { word: 'Telewizor', hint: 'Duży ekran do oglądania' },
    { word: 'Konsola', hint: 'Gry wideo' },
    { word: 'Mikrofon', hint: 'Nagrywanie głosu' },
    { word: 'Skanery', hint: 'Czytanie dokumentów' },
    { word: 'Projektor', hint: 'Obrazy na ścianę' },
    { word: 'Dokładniej', hint: 'Wygodne do pracy' },
  ],
  Przyroda: [
    { word: 'Las', hint: 'Drzewa, zwierzęta' },
    { word: 'Góra', hint: 'Wysoka, alpinizm' },
    { word: 'Rzeka', hint: 'Płynąca woda' },
    { word: 'Jezioro', hint: 'Stojąca woda' },
    { word: 'Morze', hint: 'Slona woda, fale' },
    { word: 'Ocean', hint: 'Ogromna woda' },
    { word: 'Plaża', hint: 'Piasek, morze' },
    { word: 'Pustynia', hint: 'Piaski, sucho' },
    { word: 'Tundra', hint: 'Mróz, arcktyka' },
    { word: 'Sawanna', hint: 'Afryka, trawy' },
    { word: 'Dżungla', hint: 'Gęsty las' },
    { word: 'Wulkan', hint: 'Lawa, gorąco' },
    { word: 'Jaskinia', hint: 'Podziemna' },
    { word: 'Wodospad', hint: 'Padająca woda' },
    { word: 'Chmura', hint: 'W niebie, woda' },
    { word: 'Burza', hint: 'Grzmot, błyskawica' },
    { word: 'Śnieg', hint: 'Biały, zima' },
    { word: 'Lód', hint: 'Zamrożona woda' },
    { word: 'Grad', hint: 'Ciężkie kulki lodu' },
    { word: 'Tęcza', hint: 'Kolorowa, po deszczu' },
  ],
  Muzyka: [
    { word: 'Rock', hint: 'Gitary, energiczny' },
    { word: 'Pop', hint: 'Popularna, katchy' },
    { word: 'Rap', hint: 'Rymowanka, beat' },
    { word: 'Jazz', hint: 'Improwizacyjny, trąbka' },
    { word: 'Blues', hint: 'Smutny, gitara' },
    { word: 'Klasyka', hint: 'Poważna, orkiestra' },
    { word: 'Elektronika', hint: 'Syntezer, DJ' },
    { word: 'Metal', hint: 'Agresywny rock' },
    { word: 'Country', hint: 'Wiejski, gitary' },
    { word: 'Reggae', hint: 'Jamajki, ritm' },
    { word: 'Hip-Hop', hint: 'Rap, kultura' },
    { word: 'R&B', hint: 'Soul, melodyjny' },
    { word: 'Techno', hint: 'Pulsujący, taniec' },
    { word: 'House', hint: 'Taneczny, party' },
    { word: 'Opera', hint: 'Śpiewana sztuka' },
    { word: 'Ludowa', hint: 'Tradycyjna, taniec' },
    { word: 'Soul', hint: 'Emocjonalna, głos' },
    { word: 'Funk', hint: 'Groovy, taneczne' },
    { word: 'Indie', hint: 'Niezależna, alternatywa' },
    { word: 'Punk', hint: 'Rebelia, szybka' },
  ],
};

export function getRandomWord(category: string): { word: string; hint: string } {
  const words = WORD_CATEGORIES[category as keyof typeof WORD_CATEGORIES];
  if (!words || words.length === 0) {
    return { word: 'Sekret', hint: 'Niespodziewane' };
  }
  const randomWord = words[Math.floor(Math.random() * words.length)];
  return randomWord;
}

export function getRandomCategory(): string {
  const categories = Object.keys(WORD_CATEGORIES);
  return categories[Math.floor(Math.random() * categories.length)];
}
